syms q4 q5 q6 dq4 dq5 dq6 ddq4 ddq5 ddq6 Iyy Izz Ixx Q4 Q5 Q6

EL4 = (-(0.5*Iyy - 0.5*Izz)*(cos(q5)^2)*(cos(q6)^2)*ddq4 + ...
       (Iyy + Izz)*sin(q6)*cos(q5)*cos(q6)*ddq5 - ...
       Ixx*sin(q5)*ddq6 + ...
       2*sin(q5)*cos(q5)*(Ixx + (Iyy - Izz)*cos(q6)^2)*dq4*dq5 + ...
       sin(q6)*cos(q6)*((Iyy-Izz)*cos(q5)^2 - Ixx)*dq4*dq6 - ...
       Q4);

EL5 = ((Iyy + Izz)*sin(q6)*cos(q5)*cos(q6)*ddq4 + ...
       (Izz + (Iyy - Izz)*cos(q6)^2)*ddq5 + ...
       sin(q5)*cos(q5)*(Ixx + (Iyy - Izz)*cos(q6)^2)*dq4^2 - ...
       2*(Iyy - Izz)*sin(q6)*cos(q6)*dq5*dq6 + ...
       cos(q5)*(Ixx +(Iyy + Izz)*cos(2*q6))*dq4*dq6 - ...
       Q5);

EL6 = (-Ixx*sin(q5)*ddq4 + ...
       Ixx*ddq6 - ...
       sin(q6)*cos(q6)*((Iyy-Izz)*cos(q5)^2 + Iyy)*dq4^2 + ...
       (Iyy-Izz)*sin(q6)*cos(q6)*dq5^2 - ...
       cos(q5)*(Ixx + (Iyy + Izz)*cos(2*q6))*dq4*dq5 - ...
       Q6);

eqns=[EL4 EL5 EL6];
S=solve(eqns, [ddq4 ddq5 ddq6], 'ReturnConditions', true);
